# Désactive toutes les commandes
forbiden_all: true

# Message lors des commandes interdites
forbiden_message: '&c[✕] Utilisez le Menu'

# Liste des commandes interdites
forbiden_commands:
  - '?'
  - 'reload'
  - 'help'
  - 'bal'
  - 'balancetop'
  - 'baltop'
  - 'eco'
  - 'economy'
  - 'money'
  - 'pay'
  - 'balance'
  - 'holo'
  - '/br'
  - '/brush'
  - '/desel'
  - '/deselect'
  - '/sel'
  - '/toggleplace'
  - ';'
  - 'br'
  - 'brush'
  - 'editshop'
  - 'hd'
  - 'hologram'
  - 'holograms'
  - 'icanhasbukkit'
  - 'lp'
  - 'luckperms'
  - 'mv'
  - 'mvanchor'
  - 'mvanchors'
  - 'mvc'
  - 'mvcheck'
  - 'mvcl'
  - 'mvclone'
  - 'mvco'
  - 'mvconf'
  - 'mvconfig'
  - 'mvconfirm'
  - 'mvcoord'
  - 'mvcreate'
  - 'mvdebug'
  - 'mvdelete'
  - 'mvenv'
  - 'mvgamerule'
  - 'mvgamerules'
  - 'mvgenerators'
  - 'mvgens'
  - 'mvh'
  - 'mvhelp'
  - 'mvi'
  - 'mvim'
  - 'mvimport'
  - 'mvinfo'
  - 'mvl'
  - 'mvlist'
  - 'mvload'
  - 'mvm'
  - 'mvmadd'
  - 'mvmclear'
  - 'mvmdelete'
  - 'mvmodify'
  - 'mvmremove'
  - 'mvmset'
  - 'mvpurge'
  - 'mvr'
  - 'mvregen'
  - 'mvreload'
  - 'mvremove'
  - 'mvrule'
  - 'mvrules'
  - 'mvs'
  - 'mvscript'
  - 'mvsearch'
  - 'mvsets'
  - 'mvsetspawn'
  - 'mvsilent'
  - 'mvspawn'
  - 'mvss'
  - 'mvtp'
  - 'mvunload'
  - 'mvv'
  - 'mvver'
  - 'mvversion'
  - 'mvw'
  - 'mvwho'
  - 'none'
  - 'perm'
  - 'permission'
  - 'permissions'
  - 'perms'
  - 'region'
  - 'regions'
  - 'rg'
  - 'sell'
  - 'sellall'
  - 'sellgui'
  - 'shop'
  - 'sreload'
  - 'teammsg'
  - 'tm'
  - 'toggleplace'
  - 'tool'
  - 'trigger'
  - 'we'
  - 'worldedit'
  - 'city'
  - 'npc'
  - 'citizens'
  - 'pl'
  - 'plugins'
  - 'grade'
  - 'menu'
  - 'duel'
  - 'cmd'

  